name: png2webp directory

on:
  workflow_dispatch:
    inputs:
      DIRECTORY:
        description: 'Directory of files to convert'
        required: true

jobs:
  convert-all:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Install webp
      run: |
        sudo apt install webp

    - name: Convert all
      run: |
        cd ${{ github.event.inputs.DIRECTORY }}
        for f in *.png; do cwebp -o ${f%.*}.webp; done

    - name: Commit and push 
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'commit it'
        add: '*.png'
